### ISSUE TITLE
Currently doesn't work...

### ISSUE THREAD

**Issue by ST-2** [Kief5555/kahoot-flooder#2]
Console error is this :  
---------------------------------------------------------------------------------------------------------------------------------
⠇ Joining bots, please wait../home/runner/KaFlood-1/node_modules/kahoot.js-updated/src/modules/backup.js:39
      this.quiz.quizQuestionAnswers = recover.defaultQuizData.quizQuestionAnswers;
                                                              ^

TypeError: Cannot read property 'quizQuestionAnswers' of undefined
    at Object.handlers.recovery (/home/runner/KaFlood-1/node_modules/kahoot.js-updated/src/modules/backup.js:39:63)
    at Client._message (/home/runner/KaFlood-1/node_modules/kahoot.js-updated/src/kahoot.js:345:23)
    at WebSocket.<anonymous> (/home/runner/KaFlood-1/node_modules/kahoot.js-updated/src/kahoot.js:298:14)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/home/runner/KaFlood-1/node_modules/ws/lib/websocket.js:1022:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/home/runner/KaFlood-1/node_modules/ws/lib/receiver.js:522:14)
    at Receiver.getData (/home/runner/KaFlood-1/node_modules/ws/lib/receiver.js:440:17)
    at Receiver.startLoop (/home/runner/KaFlood-1/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/home/runner/KaFlood-1/node_modules/ws/lib/receiver.js:83:10)
exit status 1
---------------------------------------------------------------------------------------------------------------------------------

Hope that helps!

**Comment by Kief5555** [comment]
Hey!

This project is starting to get patched left and right from kahoot, meaning it's unstable. Currently, it can only joins 1 bot per minute, which is very slow compared to a year ago. 

This means I will not longer support this project. However, I plan to make a new one soon.
